### ISSUE TITLE
Reaping Zombie (AKA Defunct) Processes

### ISSUE THREAD

**Issue by peterstory** [psi-4ward/docker-icinga2#1]
First off, thanks for the great image! I've been using it for several months, and it works great. I have encountered one problem, though: lots of zombie (AKA defunct) processes. For example:

```
996       4689  0.1  1.2 674556 24908 ?        Ssl  Mar22  76:36  |   |       \_ /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon --log-level warning --include /etc/icinga2
996       4725  0.0  0.2 510344  5456 ?        S    Mar22  13:39  |   |       |   \_ /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon --log-level warning --include /etc/icinga2
996      30203  0.0  0.0      0     0 ?        ZN   Mar22   0:00  |   |       \_ [nslookup] <defunct>
996        864  0.0  0.0      0     0 ?        ZN   Mar23   0:00  |   |       \_ [ping] <defunct>
996        870  0.0  0.0      0     0 ?        ZN   Mar23   0:00  |   |       \_ [ping] <defunct>
996      21735  0.0  0.0      0     0 ?        ZN   Mar23   0:00  |   |       \_ [ping] <defunct>
996      24262  0.0  0.0      0     0 ?        ZN   Mar23   0:00  |   |       \_ [mail] <defunct>
996      24651  0.0  0.0      0     0 ?        ZN   Mar23   0:00  |   |       \_ [mail] <defunct>
996       8803  0.0  0.0      0     0 ?        ZN   Mar23   0:00  |   |       \_ [nslookup] <defunct>
996       1309  0.0  0.0      0     0 ?        ZN   Mar23   0:00  |   |       \_ [nslookup] <defunct>
996      14822  0.0  0.0      0     0 ?        ZN   Mar23   0:00  |   |       \_ [nslookup] <defunct>
...
```

Note the `<defunct>` processes. After about a month, I have hundreds of them, and I'm only running a few checks. The only way for me to remove them is to restart my `psitrax/icinga2` container. 

I wonder whether the reason for this is because your image isn't written with an init system, which would claim these defunct processes. But I'm not sure that's the reason, because the parent process, `icinga2`, is still alive. 

See this article for more info: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
If the problem was the parent process terminating, they suggest using this script as entrypoint: https://github.com/phusion/baseimage-docker/blob/rel-0.9.16/image/bin/my_init

**Comment by psi-4ward** [comment]
You're right, I have some ssh defunct too. Please contact me in Skype. Hopefully I'll find some time next days.

Cause Icinga is the one who spawns the processes I assumed it does the reaping.
